export const BIOMES = {
  forest: {
    skyTop: '#0a1628', skyHorizon: '#1a3a2a',
    fogColor: '#1a2e1a', fogDensity: 0.018,
    groundColors: ['#2d4a1e', '#1a3012', '#3d5c2a'],
    ambientColor: '#8fbb6a', ambientIntensity: 0.4,
    sunColor: '#fff5d0', sunIntensity: 1.2,
    particleType: 'spores',
    heightScale: 12, roughness: 0.7, octaves: 6,
    interactableTypes: ['ancient_tree', 'glowing_mushroom', 'hidden_path', 'creature_den'],
  },
  cave: {
    skyTop: '#000000', skyHorizon: '#050510',
    fogColor: '#0a0a18', fogDensity: 0.04,
    groundColors: ['#1a1a2e', '#0d0d1a', '#2a1a3e'],
    ambientColor: '#4040ff', ambientIntensity: 0.15,
    sunColor: '#6060ff', sunIntensity: 0.3,
    particleType: 'embers',
    heightScale: 6, roughness: 0.9, octaves: 4,
    interactableTypes: ['crystal_formation', 'ancient_inscription', 'underground_pool', 'bioluminescent_growth'],
  },
  ocean: {
    skyTop: '#001a3a', skyHorizon: '#003366',
    fogColor: '#003355', fogDensity: 0.025,
    groundColors: ['#003355', '#001a33', '#004466'],
    ambientColor: '#00aaff', ambientIntensity: 0.5,
    sunColor: '#aaddff', sunIntensity: 0.8,
    particleType: 'bubbles',
    heightScale: 4, roughness: 0.3, octaves: 3,
    interactableTypes: ['sunken_relic', 'sea_creature', 'pressure_vent', 'coral_arch'],
  },
  desert: {
    skyTop: '#1a0a00', skyHorizon: '#cc6600',
    fogColor: '#aa8844', fogDensity: 0.01,
    groundColors: ['#cc9944', '#aa7733', '#ddbb66'],
    ambientColor: '#ffaa44', ambientIntensity: 0.8,
    sunColor: '#ffffff', sunIntensity: 2.0,
    particleType: 'sandstorm',
    heightScale: 8, roughness: 0.4, octaves: 4,
    interactableTypes: ['buried_obelisk', 'sand_spirit', 'ancient_well', 'mirage_portal'],
  },
  volcanic: {
    skyTop: '#0a0000', skyHorizon: '#660000',
    fogColor: '#331100', fogDensity: 0.035,
    groundColors: ['#1a0000', '#330000', '#2a0a00'],
    ambientColor: '#ff4400', ambientIntensity: 0.6,
    sunColor: '#ff6600', sunIntensity: 1.5,
    particleType: 'embers',
    heightScale: 20, roughness: 0.85, octaves: 5,
    interactableTypes: ['lava_conduit', 'obsidian_altar', 'fire_entity', 'ancient_seal'],
  },
  cosmic: {
    skyTop: '#000005', skyHorizon: '#000015',
    fogColor: '#000010', fogDensity: 0.001,
    groundColors: ['#050510', '#030318', '#080820'],
    ambientColor: '#2020aa', ambientIntensity: 0.1,
    sunColor: '#ffffff', sunIntensity: 3.0,
    particleType: 'stars',
    heightScale: 200, roughness: 0.3, octaves: 2,
    interactableTypes: ['nebula_fragment', 'dead_star', 'void_rift', 'cosmic_entity'],
  },
  ethereal: {
    skyTop: '#1a0040', skyHorizon: '#400080',
    fogColor: '#200060', fogDensity: 0.03,
    groundColors: ['#2a0060', '#1a0040', '#350080'],
    ambientColor: '#aa44ff', ambientIntensity: 0.7,
    sunColor: '#cc88ff', sunIntensity: 1.0,
    particleType: 'wisps',
    heightScale: 5, roughness: 0.5, octaves: 4,
    interactableTypes: ['memory_echo', 'spirit_gate', 'resonance_crystal', 'forgotten_name'],
  },
  microorganism: {
    skyTop: '#001a00', skyHorizon: '#003300',
    fogColor: '#002200', fogDensity: 0.05,
    groundColors: ['#003300', '#001a00', '#004400'],
    ambientColor: '#44ff44', ambientIntensity: 0.9,
    sunColor: '#88ff88', sunIntensity: 1.5,
    particleType: 'microparticles',
    heightScale: 0.5, roughness: 0.95, octaves: 8,
    interactableTypes: ['cell_membrane', 'protein_cluster', 'enzyme_vortex', 'dna_strand'],
  },
  tundra: {
    skyTop: '#050a18', skyHorizon: '#1a2a44',
    fogColor: '#aaccdd', fogDensity: 0.02,
    groundColors: ['#ddeeff', '#aabbcc', '#eef5ff'],
    ambientColor: '#88aacc', ambientIntensity: 0.5,
    sunColor: '#ffeedd', sunIntensity: 0.7,
    particleType: 'snow',
    heightScale: 10, roughness: 0.55, octaves: 5,
    interactableTypes: ['frozen_titan', 'aurora_rift', 'permafrost_relic', 'ice_oracle'],
  },
  mushroom_forest: {
    skyTop: '#0a0520', skyHorizon: '#1a0a35',
    fogColor: '#150a30', fogDensity: 0.022,
    groundColors: ['#3a1060', '#25083a', '#4a1a70'],
    ambientColor: '#ff44aa', ambientIntensity: 0.6,
    sunColor: '#ff88cc', sunIntensity: 0.9,
    particleType: 'spores',
    heightScale: 9, roughness: 0.6, octaves: 5,
    interactableTypes: ['spore_oracle', 'giant_cap', 'mycelium_network', 'spore_beast'],
  },
};

export const SCALE_LEVELS = {
  COSMIC: { label: 'Cosmic', terrainSize: 8000, heightMultiplier: 500, cameraSpeed: 15, fogMult: 0.1 },
  WORLD:  { label: 'World',  terrainSize: 2000, heightMultiplier: 80,  cameraSpeed: 3,  fogMult: 0.5 },
  HUMAN:  { label: 'Human',  terrainSize: 300,  heightMultiplier: 12,  cameraSpeed: 0.35, fogMult: 1 },
  MICRO:  { label: 'Micro',  terrainSize: 30,   heightMultiplier: 1.5, cameraSpeed: 0.04, fogMult: 2 },
  NANO:   { label: 'Nano',   terrainSize: 3,    heightMultiplier: 0.15, cameraSpeed: 0.004, fogMult: 4 },
};

export const getBiome = (name) => BIOMES[name] || BIOMES.forest;
export const getScale = (name) => SCALE_LEVELS[name] || SCALE_LEVELS.HUMAN;
